<a href="https://colab.research.google.com/github/donghyuun/deep-learning/blob/main/lab_07_1_learning_rate_and_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf
import numpy as np

# 데이터
x_data = np.array([[1, 2, 1],
                   [1, 3, 2],
                   [1, 3, 4],
                   [1, 5, 5],
                   [1, 7, 5],
                   [1, 2, 5],
                   [1, 6, 6],
                   [1, 7, 7]], dtype=np.float32)

y_data = np.array([[0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1],
                   [0, 1, 0],
                   [0, 1, 0],
                   [0, 1, 0],
                   [1, 0, 0],
                   [1, 0, 0]], dtype=np.float32)

# 테스트 데이터
x_test = np.array([[2, 1, 1],
                   [3, 1, 2],
                   [3, 3, 4]], dtype=np.float32)

y_test = np.array([[0, 0, 1],
                   [0, 0, 1],
                   [0, 0, 1]], dtype=np.float32)

# 학습률
learning_rate = 1e-10

# 모델 정의
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=3, input_dim=3, activation='softmax')
])

# 모델 컴파일
model.compile(
    loss='categorical_crossentropy',
    optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate),
    metrics=['accuracy']
)

# 모델 학습
model.fit(x_data, y_data, epochs=1000, verbose=0)

# 예측
predictions = model.predict(x_test)
predicted_classes = tf.argmax(predictions, axis=1)

print("Predictions (class probabilities):")
print(predictions)
print("Predicted classes:")
print(predicted_classes.numpy())

# 정확도 계산
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Predictions (class probabilities):
[[0.56760514 0.3297119  0.10268295]
 [0.49931288 0.46538526 0.03530192]
 [0.08217625 0.9124414  0.00538243]]
Predicted classes:
[0 0 1]
Test Loss: 3.6148
Test Accuracy: 0.0000
