<a href="https://colab.research.google.com/github/donghyuun/deep-learning/blob/main/lab_06_1_softmax_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np

# Data
x_data = np.array([
    [1, 2, 1, 1],
    [2, 1, 3, 2],
    [3, 1, 3, 4],
    [4, 1, 5, 5],
    [1, 7, 5, 5],
    [1, 2, 5, 6],
    [1, 6, 6, 6],
    [1, 7, 7, 7]
], dtype=np.float32)

y_data = np.array([
    [0, 0, 1],  # Class 2
    [0, 0, 1],  # Class 2
    [0, 0, 1],  # Class 2
    [0, 1, 0],  # Class 1
    [0, 1, 0],  # Class 1
    [0, 1, 0],  # Class 1
    [1, 0, 0],  # Class 0
    [1, 0, 0]   # Class 0
], dtype=np.float32)

nb_classes = 3  # Number of classes

# Variables
W = tf.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')

# Hypothesis (softmax)
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

# Cost function
def cost_fn(X, Y):
    logits = tf.matmul(X, W) + b
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=logits))
    return cost

# Training
learning_rate = 0.1
optimizer = tf.optimizers.SGD(learning_rate)

for step in range(2001):
    with tf.GradientTape() as tape:
        cost = cost_fn(x_data, y_data)
    gradients = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))

    if step % 200 == 0:
        print(f"Step: {step}, Cost: {cost.numpy()}")

# Testing with multiple inputs
test_data = np.array([
    [1, 11, 7, 9],
    [1, 3, 4, 3],
    [1, 1, 0, 1]
], dtype=np.float32)

predictions = hypothesis(test_data)
predicted_classes = tf.argmax(predictions, axis=1)

print("Softmax outputs:")
print(predictions.numpy())
print("Predicted classes:")
print(predicted_classes.numpy())


Step: 0, Cost: 11.688674926757812
Step: 200, Cost: 0.5400075316429138
Step: 400, Cost: 0.4292927086353302
Step: 600, Cost: 0.34861260652542114
Step: 800, Cost: 0.2728123068809509
Step: 1000, Cost: 0.2351999133825302
Step: 1200, Cost: 0.21289938688278198
Step: 1400, Cost: 0.19444595277309418
Step: 1600, Cost: 0.17888705432415009
Step: 1800, Cost: 0.16558116674423218
Step: 2000, Cost: 0.15407070517539978
Softmax outputs:
[[8.6628357e-03 9.9132735e-01 9.7542170e-06]
 [8.0995786e-01 1.7170502e-01 1.8337127e-02]
 [9.7618615e-09 3.5128684e-04 9.9964869e-01]]
Predicted classes:
[1 0 2]
