<a href="https://colab.research.google.com/github/donghyuun/deep-learning/blob/main/lab_04_1_Multi_variable_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# data and label
# Matrix 사용 X
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random.normal((1,)))
w2 = tf.Variable(tf.random.normal((1,)))
w3 = tf.Variable(tf.random.normal((1,)))
b  = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])

    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |     404.3058
   50 |       7.0533
  100 |       2.6419
  150 |       2.5894
  200 |       2.5852
  250 |       2.5817
  300 |       2.5781
  350 |       2.5745
  400 |       2.5710
  450 |       2.5674
  500 |       2.5639
  550 |       2.5604
  600 |       2.5568
  650 |       2.5534
  700 |       2.5499
  750 |       2.5464
  800 |       2.5429
  850 |       2.5395
  900 |       2.5360
  950 |       2.5326
 1000 |       2.5291


In [12]:
# Matrix 사용 O

data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable(tf.random.normal((3, 1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))

    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])

    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |    12.1675
  100 |     4.0823
  200 |     4.0606
  300 |     4.0400
  400 |     4.0194
  500 |     3.9990
  600 |     3.9788
  700 |     3.9586
  800 |     3.9385
  900 |     3.9185
 1000 |     3.8987
 1100 |     3.8790
 1200 |     3.8594
 1300 |     3.8398
 1400 |     3.8204
 1500 |     3.8010
 1600 |     3.7818
 1700 |     3.7628
 1800 |     3.7438
 1900 |     3.7248
 2000 |     3.7060


In [15]:
y # labels, 실제값

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)

In [16]:
predict(X).numpy() # prediction, 예측값

array([[148.61539],
       [186.58096],
       [179.85838],
       [195.77261],
       [144.12184]], dtype=float32)

In [17]:
# 새로운 데이터에 대한 예측
predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy()

array([[181.47426],
       [170.41692]], dtype=float32)