<a href="https://colab.research.google.com/github/donghyuun/deep-learning/blob/main/lab_04_1_Multi_variable_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# data and label
# Matrix 사용 X
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random.normal((1,)))
w2 = tf.Variable(tf.random.normal((1,)))
w3 = tf.Variable(tf.random.normal((1,)))
b  = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])

    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |     404.3058
   50 |       7.0533
  100 |       2.6419
  150 |       2.5894
  200 |       2.5852
  250 |       2.5817
  300 |       2.5781
  350 |       2.5745
  400 |       2.5710
  450 |       2.5674
  500 |       2.5639
  550 |       2.5604
  600 |       2.5568
  650 |       2.5534
  700 |       2.5499
  750 |       2.5464
  800 |       2.5429
  850 |       2.5395
  900 |       2.5360
  950 |       2.5326
 1000 |       2.5291


In [12]:
# Matrix 사용 O

data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable(tf.random.normal((3, 1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))

    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])

    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |    12.1675
  100 |     4.0823
  200 |     4.0606
  300 |     4.0400
  400 |     4.0194
  500 |     3.9990
  600 |     3.9788
  700 |     3.9586
  800 |     3.9385
  900 |     3.9185
 1000 |     3.8987
 1100 |     3.8790
 1200 |     3.8594
 1300 |     3.8398
 1400 |     3.8204
 1500 |     3.8010
 1600 |     3.7818
 1700 |     3.7628
 1800 |     3.7438
 1900 |     3.7248
 2000 |     3.7060


In [15]:
y # labels, 실제값

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)

In [16]:
predict(X).numpy() # prediction, 예측값

array([[148.61539],
       [186.58096],
       [179.85838],
       [195.77261],
       [144.12184]], dtype=float32)

In [17]:
# 새로운 데이터에 대한 예측
predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy()

array([[181.47426],
       [170.41692]], dtype=float32)

In [18]:
# Lab 4 Multi-variable linear regression (다중 선형 회귀)
import tensorflow as tf
import numpy as np

# CSV 파일에서 데이터 로드 (data-01-test-score.csv 파일에서 데이터 읽기)
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32, skiprows=1)
# x_data: 입력 데이터 (시험 점수 3개: EXAM1, EXAM2, EXAM3)
x_data = xy[:, 0:-1]
# y_data: 출력 데이터 (최종 점수: FINAL)
y_data = xy[:, [-1]]

# 데이터 형태 출력 (x_data와 y_data의 내용 및 크기 확인)
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# 출력 예시 (예상 결과를 주석으로 작성)
'''
x_data:
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
x_data shape: (25, 3)  # 25개의 데이터 샘플, 각 샘플에 3개의 입력 값(EXAM1, EXAM2, EXAM3)

y_data:
[[152.]
 [185.]
 ...
 [149.]
 [192.]]
y_data shape: (25, 1)  # 25개의 데이터 샘플, 각 샘플에 1개의 출력 값(FINAL)
'''

# 모델 생성
tf.model = tf.keras.Sequential()  # Sequential 모델 생성 (층을 순차적으로 쌓음)

# Dense 층 추가
# - units=1: 출력 차원(최종 예측 값 y 하나만 출력)
# - input_dim=3: 입력 데이터의 차원(시험 점수 3개)
# - activation='linear': 선형 활성화 함수 (활성화 함수 없이 그대로 계산)
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))

# 모델 구조 출력 (Dense 층의 매개변수 개수 확인)
tf.model.summary()
'''
모델 구조 예시:
Layer (type)               Output Shape   Param #
=================================================================
dense (Dense)              (None, 1)      4          # 3개의 입력(weight) + 1개의 bias = 4
=================================================================
Total params: 4
Trainable params: 4
Non-trainable params: 0
'''

# 모델 컴파일
tf.model.compile(
    loss='mse',  # 손실 함수로 평균 제곱 오차(MSE) 사용
    optimizer=tf.keras.optimizers.SGD(learning_rate=1e-5)  # SGD 최적화 알고리즘 사용, 학습률 1e-5
)

# 모델 학습
# - x_data: 입력 데이터
# - y_data: 출력 데이터
# - epochs=100: 전체 데이터를 100번 반복 학습
history = tf.model.fit(x_data, y_data, epochs=100)

# 새로운 데이터로 예측 수행
# np.array를 사용해 입력 데이터를 NumPy 배열로 변환 (모델이 배열 형태의 데이터를 입력받기 때문)
print("Your score will be ", tf.model.predict(np.array([[100, 70, 101]])))
# 예: 시험 점수가 EXAM1=100, EXAM2=70, EXAM3=101인 경우의 예측 점수 출력

print("Other scores will be ", tf.model.predict(np.array([[60, 70, 110], [90, 100, 80]])))
# 예: 두 개의 입력 데이터(EXAM1, EXAM2, EXAM3)에 대해 예측 점수 출력
# 첫 번째: EXAM1=60, EXAM2=70, EXAM3=110
# 두 번째: EXAM1=90, EXAM2=100, EXAM3=80


[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 
x_data shape: (6, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]] 
y_data shape: (6, 1)


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4 (16.00 B)

 Trainable params: 4 (16.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - loss: 18062.6348
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 6659.1914
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 2459.8035
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 913.3514
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 343.8597
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 134.1390
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 56.9065
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 28.4635
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 17.9874
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 14.1280
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 12.7050
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 12.1793
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 11.9840
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 11.9104
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1